"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@heroui/react";
import { MarkdownEditor } from "@/components/markdown-editor";

export function DropEditor({slug,title,markdown}:{slug:string;title:string;markdown:string}){const router=useRouter();const cancelDeleteRef=useRef<HTMLButtonElement>(null);const [state,setState]=useState<"idle"|"saving"|"saved"|"error">("idle");const [deleteState,setDeleteState]=useState<"idle"|"confirming"|"deleting"|"error">("idle");const [error,setError]=useState("");const [deleteError,setDeleteError]=useState("");const [content,setContent]=useState(markdown);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setState("saving");setError("");const form=new FormData(event.currentTarget);try{const response=await fetch(`/api/v1/drops/${slug}/manage`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({title:form.get("title"),markdown:content})});const data=await response.json().catch(()=>({}));if(response.ok)setState("saved");else{setError(data.error||"Could not save changes.");setState("error")}}catch{setError("Changes could not be saved. Check your connection and try again.");setState("error")}}
  function askToDelete(){setDeleteError("");setDeleteState("confirming");requestAnimationFrame(()=>cancelDeleteRef.current?.focus())}
  async function deleteChit(){setDeleteState("deleting");setDeleteError("");try{const response=await fetch(`/api/v1/drops/${slug}/manage`,{method:"DELETE"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Could not delete this chit.");router.replace("/dashboard?deleted=1");router.refresh()}catch(reason){setDeleteError(reason instanceof Error?reason.message:"Could not delete this chit. Try again.");setDeleteState("error")}}
  const busy=state==="saving"||deleteState==="deleting";
  return <form className="composer" onSubmit={submit}><div className="composer-head"><span className="route-label">Editing /{slug}</span><div className="editor-actions"><Link className="button-secondary" href={`/${slug}`}>View chit</Link><Button className="button-primary" type="submit" isDisabled={busy}>{state==="saving"?"Saving…":"Save changes"}</Button></div></div>
    <label className="title-field"><span>Chit title</span><input name="title" required maxLength={120} defaultValue={title}/></label><MarkdownEditor value={content} onChange={(next)=>{setContent(next);if(state==="saved")setState("idle")}}/><div className="composer-foot"><Button className="button-secondary button-danger" type="button" onPress={askToDelete} isDisabled={busy||deleteState==="confirming"}>Delete chit</Button><span className="form-note">{state==="saved"?"Saved":"Changes update the same link."}</span></div>{(deleteState==="confirming"||deleteState==="deleting"||deleteState==="error")&&<section className="delete-confirmation" aria-labelledby="delete-chit-title"><div><strong id="delete-chit-title">Delete this chit?</strong><p>The public link and its Markdown will be gone for good.</p>{deleteState==="error"&&<p className="delete-error" role="alert">{deleteError}</p>}</div><div className="delete-actions"><Button ref={cancelDeleteRef} className="button-secondary" type="button" onPress={()=>setDeleteState("idle")} isDisabled={deleteState==="deleting"}>Cancel</Button><Button className="button-primary button-delete-confirm" type="button" onPress={deleteChit} isDisabled={deleteState==="deleting"}>{deleteState==="deleting"?"Deleting…":"Delete forever"}</Button></div></section>}{state==="saved"&&<div className="notice success" role="status">Chit updated.</div>}{state==="error"&&<div className="notice error" role="alert">{error}</div>}</form>}
